// Generated by gencpp from file rrm_msgs/Move.msg
// DO NOT EDIT!


#ifndef RRM_MSGS_MESSAGE_MOVE_H
#define RRM_MSGS_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <rrm_msgs/MoveRequest.h>
#include <rrm_msgs/MoveResponse.h>


namespace rrm_msgs
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace rrm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rrm_msgs::Move > {
  static const char* value()
  {
    return "dcc6d40667e961b4ed6e622fe794df0c";
  }

  static const char* value(const ::rrm_msgs::Move&) { return value(); }
};

template<>
struct DataType< ::rrm_msgs::Move > {
  static const char* value()
  {
    return "rrm_msgs/Move";
  }

  static const char* value(const ::rrm_msgs::Move&) { return value(); }
};


// service_traits::MD5Sum< ::rrm_msgs::MoveRequest> should match
// service_traits::MD5Sum< ::rrm_msgs::Move >
template<>
struct MD5Sum< ::rrm_msgs::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rrm_msgs::Move >::value();
  }
  static const char* value(const ::rrm_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rrm_msgs::MoveRequest> should match
// service_traits::DataType< ::rrm_msgs::Move >
template<>
struct DataType< ::rrm_msgs::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::rrm_msgs::Move >::value();
  }
  static const char* value(const ::rrm_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rrm_msgs::MoveResponse> should match
// service_traits::MD5Sum< ::rrm_msgs::Move >
template<>
struct MD5Sum< ::rrm_msgs::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rrm_msgs::Move >::value();
  }
  static const char* value(const ::rrm_msgs::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rrm_msgs::MoveResponse> should match
// service_traits::DataType< ::rrm_msgs::Move >
template<>
struct DataType< ::rrm_msgs::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::rrm_msgs::Move >::value();
  }
  static const char* value(const ::rrm_msgs::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RRM_MSGS_MESSAGE_MOVE_H
