// Generated by gencpp from file Zad1/Data.msg
// DO NOT EDIT!


#ifndef ZAD1_MESSAGE_DATA_H
#define ZAD1_MESSAGE_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Zad1
{
template <class ContainerAllocator>
struct Data_
{
  typedef Data_<ContainerAllocator> Type;

  Data_()
    : name()
    , velocity(0.0)  {
    }
  Data_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::Zad1::Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Zad1::Data_<ContainerAllocator> const> ConstPtr;

}; // struct Data_

typedef ::Zad1::Data_<std::allocator<void> > Data;

typedef boost::shared_ptr< ::Zad1::Data > DataPtr;
typedef boost::shared_ptr< ::Zad1::Data const> DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Zad1::Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Zad1::Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Zad1::Data_<ContainerAllocator1> & lhs, const ::Zad1::Data_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Zad1::Data_<ContainerAllocator1> & lhs, const ::Zad1::Data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Zad1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Zad1::Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Zad1::Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Zad1::Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Zad1::Data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Zad1::Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Zad1::Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Zad1::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2fd9f71288435c0d2a1acae968c9052e";
  }

  static const char* value(const ::Zad1::Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2fd9f71288435c0dULL;
  static const uint64_t static_value2 = 0x2a1acae968c9052eULL;
};

template<class ContainerAllocator>
struct DataType< ::Zad1::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Zad1/Data";
  }

  static const char* value(const ::Zad1::Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Zad1::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float64 velocity\n"
;
  }

  static const char* value(const ::Zad1::Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Zad1::Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Zad1::Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Zad1::Data_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZAD1_MESSAGE_DATA_H
